language: node_js
node_js:
  - lts/*
script:
  - yarn build
cache: yarn
deploy:
  skip_cleanup: true
  provider: npm
  email: nvitaterna@gmail.com
  api_key:
    secure: sHM2z28kaY6R1YDxlGzxOOUfsi80llGV6wv1ZxTUn7ZWg3OL3o3wwN/gFQrZSexrkQ+Pz9sRENwWi8H5p5VCfQidZGK+Dhptvz9dP1JrTz27MG369tYha3FO0Txws1XdXQDn9Sbuag7WLmA2oVXZiJsg6DPSkY+5ytgmJju85BL49WfmZobgbEqDvc2+LKJKIkBNj7ofeQZ4L8GASnTEa21HHsTFqGCI79ZCYWEAnjO7QyBq7k3OWnoC62+klAeaiRx30jqcPHVPjIDAE96K6h5sVOVc+xsAe47wETGTYjlAAEM2jT25c8Ey52b6LtU4oCoAiGJnh4BSMcN+QirkWJ9cgJhs7YSavBe242NZRuSxYMb0OXT00sg4/rpmfYem72dDKJemwRI8nUDVwM1GvQ4cPIWEUmCbTVB5qagFc8UcNNeaEaoMmagQoUDV2rGQFtU25c2BlZotaMb9NXuzK1GpL42MOduM14bXKtBcjXb7Ja3S2kfeGL1rjrRlgTHNW5DBKAfYsE2W+S0n7iLbdcmF1SFsrUwEVtJK6ogJbGRdwQf6JN13hc7RhFXDTIu95YkC7pvNmifElMngVEizd03bHqbul5R8eOXK3qp+ciRC0F8+Q1h9OQXf6Ya8AwbQm6jzHK/X9pCrbyJ0/DYgrIFwkU+XgmFi8uAvBFHMY8c=
  on:
    tags: true
    repo: nvitaterna/joypad-manager
