language: node_js
node_js:
  - lts/*
script:
  - yarn build
cache: yarn
deploy:
  skip_cleanup: true
  provider: npm
  email: nvitaterna@gmail.com
  api_key:
    secure: GAVwS4yQi7OCBP2VFCRxQSroVhFV+wNPwRxtNsQqieQOQqVz+85mXxnYWmz+348yfQMjU0zE3d+j+vnMUZjtHGRwHufMC4r2eJfXX4KV0lBe7j74BbastDi/tBFn/IwZglJyRPOh0rkXJUn3Ra3BcBQMi9qts7frFGu7UJHVhdTqUJz2rigrYviXQ2g2U3N6btW6U+2fwZ9+y1eUhPDmAdClA9oHBYf0WN+VFKROhi8aNX/jBb4zzF5M/lPCpQMd1xUXU5gKKedPJ8tLCJMnGFXjBaftI1Ive8jwc7byS0OGCOm/rCSeSQz3i5OVD5mNNjN4W/rPugsy6YwAjqmaXOovkm1tbQp2cHGCy5aCpQOwflGa13D76QrsAKfE7DuQgA6tcgOvXysE6qZBpKFZ5iOJCdI5jjMrCaYDJRPHB4gv9egd1RMDAOMudBRCL56gqB8nQMI05/wcJeBmHNWWeDvzyOnIc8f8ISGUQURY/0430PX43LpGJu3728wn9WoGYOBC/JBRSeMEqBhpUBWoLg5pXfb3BjwwWw6XizB0K+y4oSReK70Ymr1nFMV3AC1J7WyMmmrvCz55937uXQtv/GxRJSVjlt2MhznES1vzttitIthH8yHCSp5XW4LcGvAeuGDTpeqHAXfO8tbUkZOUQJBVg5Eyg3BJcCmGHzJjGpw=
  on:
    tags: true
    repo: nvitaterna/joypad-manager
